export const DAILY_NUTRIENT_VALUES = {
  carbohydrate: 324, // g (탄수화물)
  protein: 55, // g (단백질)
  fat: 54, // g (지방)
  sugar: 100, // g (당류)
  sodium: 2000, // mg (나트륨)
};

export const DAILY_NUTRIENT_STANDARD = {
  ...DAILY_NUTRIENT_VALUES,
  dietaryFiber: 25, // g (식이섬유)
  saturatedFat: 15, // g (포화지방)
  cholesterol: 300, // mg (콜레스테롤)
  potassium: 3500, // mg (칼륨)
  calcium: 700, // mg (칼슘)
  iron: 12, // mg (철분)
  vitaminA: 700, // µg RE (비타민 A)
  vitaminC: 100, // mg (비타민 C)
  vitaminD: 10, // µg (비타민 D)
  vitaminE: 11, // mg α-TE (비타민 E)
  vitaminK: 70, // µg (비타민 K)
  vitaminB1: 1.2, // mg (비타민 B1, 티아민)
  vitaminB2: 1.4, // mg (비타민 B2, 리보플라빈)
  niacin: 15, // mg NE (니아신, 비타민 B3)
  vitaminB6: 1.5, // mg (비타민 B6)
  folate: 400, // µg (엽산, 비타민 B9)
  vitaminB12: 2.4, // µg (비타민 B12)
  biotin: 30, // µg (비오틴, 비타민 B7)
  pantothenicAcid: 5, // mg (판토텐산, 비타민 B5)
  phosphorus: 700, // mg (인)
  iodine: 150, // µg (요오드)
  magnesium: 315, // mg (마그네슘)
  zinc: 8.5, // mg (아연)
  selenium: 55, // µg (셀레늄)
  copper: 0.8, // mg (구리)
  manganese: 3.0, // mg (망간)
  chromium: 30, // µg (크롬)
  molybdenum: 25, // µg (몰리브덴)
};
